### ISSUE TITLE
Licensing concerns

### ISSUE THREAD

**Issue by fberasategui** [yuvaltz/Granular#23]
I have 2 main concerns here:

1 - WPF is not open source. How does that affect the legal status of the Granular project? It is safe, from a legal perspective, to write software based on Granular?

2 - Granular itself doesn't have a license statement anywhere. See http://blog.codinghorror.com/pick-a-license-any-license/

**Comment by yuvaltz** [comment]
1 - Granular is a re-implementation of WPF public APIs (and by public I mean the public access modifier in C#), under those APIs it has a very different implementation, I'm not an expert on this subject, but it seems ok, especially since there are many open source implementations of parts of the .Net framework (such as Mono) and I'm not aware of any legal issues with them ([link](http://arstechnica.com/information-technology/2009/07/microsoft-issues-patent-promise-dispels-mono-concerns/)).

2 - It has an Apache 2.0 License
https://github.com/yuvaltz/Granular/blob/master/License.txt

**Comment by fberasategui** [comment]
Thanks ;)
